In [1]:
import pandas as pd

In [2]:
import numpy as np
import re
import geopandas as gpd

In [3]:
loc = pd.read_csv("sez_data/sez_location/all_years_sez/clean_id_loc_year_type.csv", 
                  encoding='cp1252')

In [4]:
inv = pd.read_csv("sez_data/sez_investment/inv00-19.csv", 
                  encoding='cp1252')

In [5]:
empf = pd.read_csv("sez_data/sez_employment/emp_agg_f.csv", 
                  encoding='cp1252')

In [6]:
empm = pd.read_csv("sez_data/sez_employment/emp_agg_m.csv", 
                  encoding='cp1252')

In [7]:
#emp_total = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_employment/emp_agg_total.csv", 
#                  encoding='cp1252')

In [8]:
ent = pd.read_csv("sez_data/sez_enterprises/ent99_19.csv", 
                  encoding='cp1252')

In [9]:
exp_ele = pd.read_csv("sez_data/sez_expenses/exp_ele00_19.csv", 
                  encoding='cp1252')

In [10]:
exp_com = pd.read_csv("sez_data/sez_expenses/exp_com00_19.csv", 
                  encoding='cp1252')

In [11]:
exp_inf = pd.read_csv("sez_data/sez_expenses/exp_infotep00_19.csv", 
                  encoding='cp1252')

In [12]:
exp_wat = pd.read_csv("sez_data/sez_expenses/exp_water00_19.csv", 
                  encoding='cp1252')

In [13]:
exp_tss = pd.read_csv("sez_data/sez_expenses/exp_tss00_19.csv", 
                  encoding='cp1252')

In [14]:
nav = pd.read_csv("sez_data/sez_naves/nav_agg_00_16.csv", 
                  encoding='cp1252')

In [15]:
op = pd.read_csv("sez_data/sez_salary/sal_op_00_16.csv", 
                  encoding='cp1252')

In [16]:
tec = pd.read_csv("sez_data/sez_salary/sal_tec_00_16.csv", 
                  encoding='cp1252')

In [17]:
def f(df):
    #df.drop(df.columns.str.contains("par"), inplace = True)
    
    #Eliminates the original park name column 
    return df.drop(columns=df.columns[df.columns.str.contains("park")])

In [18]:
#databases = [empf, empm, emp_total, ent, exp_ele, exp_com, exp_inf, exp_wat, exp_tss, nav, op, tec]
databases = [empf, empm, ent, exp_ele, exp_com, exp_inf, exp_wat, exp_tss, nav, op, tec]

In [19]:
sez = pd.merge(loc, f(inv), on="code", how="outer")

In [20]:
for database in databases: 
    sez = pd.merge(sez, f(database), on="code", how="outer")

In [21]:
sez = sez[sez["code"] != "DOM-ZFE"]

In [22]:
sez.fillna(0, inplace=True)

In [23]:
#Puts full year on the columns names 
def rename_columns(df):
    new_columns = []
    for col in df.columns:
        if col[-2:].isdigit() and not col[-4:].isdigit():
            new_columns.append(col[:-2] + "20" + col[-2:])  
        else:
            new_columns.append(col)
    df.columns = new_columns
    return df

In [24]:
sez = rename_columns(sez)

In [25]:
sez.columns = sez.columns.str.replace("ob_f_", "ob_f")
sez.columns = sez.columns.str.replace("tec_f_", "tec_f")
sez.columns = sez.columns.str.replace("adm_f_", "adm_f")
sez.columns = sez.columns.str.replace("ob_m_", "ob_m")
sez.columns = sez.columns.str.replace("tec_m_", "tec_m")
sez.columns = sez.columns.str.replace("adm_m_", "adm_m")

In [26]:
sez.rename(columns = {"ent2099": "ent1999"}, inplace = True)

In [27]:
filter_year = ["2017", "2018", "2018", "2019", "2020", "2021", "2022", "1999"]

pattern = "|".join(filter_year)
sez_filtered = sez.drop(columns = sez.columns[sez.columns.str.contains(pattern)])

In [28]:
sez_filtered.to_csv("extracted_data/sez_data/sez_aggregated.csv", index=False)

In [29]:
sez_filtered

,code,name,latitude,longitude,start,close,type,sez_id,origin,inv2000,...,sal_tec2007,sal_tec2008,sal_tec2009,sal_tec2010,sal_tec2011,sal_tec2012,sal_tec2013,sal_tec2014,sal_tec2015,sal_tec2016
0,DOM-6NO,Zona Franca 6 de Noviembre,18.434236,-70.077097,2016.0,0.0,private,1.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2500.00
1,DOM-ALC,Los Alcarrizos,18.521192,-70.050865,1990.0,0.0,public,2.0,1.0,19853638.95,...,3446.06,2969.16,4073.59,3389.04,3762.00,3197.77,3533.52,3852.34,4420.89,4293.00
2,DOM-ALT,Villa Altagracia,18.687048,-70.180632,1988.0,0.0,private,3.0,1.0,33900000.00,...,3489.29,3026.84,4079.53,2903.04,5212.50,4772.18,4996.25,5007.53,5640.68,5610.00
3,DOM-AND,Andres,18.442336,-69.649780,2009.0,0.0,private,4.0,1.0,0.00,...,0.00,0.00,3514.00,3675.25,3654.00,6025.00,5077.00,7045.37,6936.53,7100.00
4,DOM-ARM,La Armeria,18.421294,-70.117660,1990.0,0.0,public,5.0,1.0,8620740.19,...,1954.00,2551.00,3551.60,3893.25,3359.33,3131.93,4402.00,3956.30,4300.90,4187.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,DOM-VEG,La Vega,19.246732,-70.556490,1987.0,0.0,public,91.0,1.0,45018217.52,...,3836.31,2984.12,3021.27,3190.84,3356.29,3686.81,3737.21,4189.40,4754.71,4671.84
92,DOM-VER,Luperon Verde,19.793250,-70.680905,2019.0,0.0,private,92.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
93,DOM-VIS,Bella Vista,18.613215,-69.708447,2004.0,0.0,private,93.0,1.0,0.00,...,0.00,4569.00,4615.00,5375.00,4698.00,6863.00,6433.17,7015.64,4450.00,4500.00
94,DOM-YAQ,Parque Industrial y de Servicios Yaque,19.469724,-70.714373,2010.0,0.0,private,94.0,1.0,0.00,...,0.00,0.00,0.00,3439.60,4800.00,3417.45,3807.43,2897.10,3996.96,5841.01
96,DOM-ZOF,Zofinma (Mao),19.553957,-71.091628,1993.0,2006.0,private,95.0,1.0,413004.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [30]:
columns = sez_filtered.columns[sez_filtered.columns.str.contains("20\d{2}")]

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hendr\AppData\Local\Temp\ipykernel_538632\1402232561.py:1: SyntaxWarning: invalid escape sequence '\d'
  columns = sez_filtered.columns[sez_filtered.columns.str.contains("20\d{2}")]

In [31]:
columns_mod = [re.sub(r'(\D)(20\d{2})$', r'\1_\2', col.strip()) for col in columns]

In [32]:
sez_data_backup = sez_filtered

In [33]:
for col, col_mod in zip(columns, columns_mod):
    print(f"old name {col}, new name {col_mod}")
    sez_filtered.rename(columns={col:col_mod}, inplace=True)

old name inv2000, new name inv_2000
old name inv2001, new name inv_2001
old name inv2002, new name inv_2002
old name inv2003, new name inv_2003
old name inv2004, new name inv_2004
old name inv2005, new name inv_2005
old name inv2006, new name inv_2006
old name inv2007, new name inv_2007
old name inv2008, new name inv_2008
old name inv2009, new name inv_2009
old name inv2010, new name inv_2010
old name inv2011, new name inv_2011
old name inv2012, new name inv_2012
old name inv2013, new name inv_2013
old name inv2014, new name inv_2014
old name inv2015, new name inv_2015
old name inv2016, new name inv_2016
old name ob_f2000, new name ob_f_2000
old name tec_f2000, new name tec_f_2000
old name adm_f2000, new name adm_f_2000
old name ob_f2001, new name ob_f_2001
old name tec_f2001, new name tec_f_2001
old name adm_f2001, new name adm_f_2001
old name ob_f2002, new name ob_f_2002
old name tec_f2002, new name tec_f_2002
old name adm_f2002, new name adm_f_2002
old name ob_f2003, new name ob_f_2003
old name tec_f2003, new name tec_f_2003
old name adm_f2003, new name adm_f_2003
old name ob_f2004, new name ob_f_2004
old name tec_f2004, new name tec_f_2004
old name adm_f2004, new name adm_f_2004
old name ob_f2005, new name ob_f_2005
old name tec_f2005, new name tec_f_2005
old name adm_f2005, new name adm_f_2005
old name ob_f2006, new name ob_f_2006
old name tec_f2006, new name tec_f_2006
old name adm_f2006, new name adm_f_2006
old name ob_f2007, new name ob_f_2007
old name tec_f2007, new name tec_f_2007
old name adm_f2007, new name adm_f_2007
old name ob_f2008, new name ob_f_2008
old name tec_f2008, new name tec_f_2008
old name adm_f2008, new name adm_f_2008
old name ob_f2009, new name ob_f_2009
old name tec_f2009, new name tec_f_2009
old name adm_f2009, new name adm_f_2009
old name ob_f2010, new name ob_f_2010
old name tec_f2010, new name tec_f_2010
old name adm_f2010, new name adm_f_2010
old name ob_f2011, new name ob_f_2011
old name tec_f2011, new name tec_f_2011
old name adm_f2011, new name adm_f_2011
old name ob_f2012, new name ob_f_2012
old name tec_f2012, new name tec_f_2012
old name adm_f2012, new name adm_f_2012
old name ob_f2014, new name ob_f_2014
old name tec_f2014, new name tec_f_2014
old name adm_f2014, new name adm_f_2014
old name ob_f2015, new name ob_f_2015
old name tec_f2015, new name tec_f_2015
old name adm_f2015, new name adm_f_2015
old name ob_f2016, new name ob_f_2016
old name tec_f2016, new name tec_f_2016
old name adm_f2016, new name adm_f_2016
old name ob_m2000, new name ob_m_2000
old name tec_m2000, new name tec_m_2000
old name adm_m2000, new name adm_m_2000
old name ob_m2001, new name ob_m_2001
old name tec_m2001, new name tec_m_2001
old name adm_m2001, new name adm_m_2001
old name ob_m2002, new name ob_m_2002
old name tec_m2002, new name tec_m_2002
old name adm_m2002, new name adm_m_2002
old name ob_m2003, new name ob_m_2003
old name tec_m2003, new name tec_m_2003
old name adm_m2003, new name adm_m_2003
old name ob_m2004, new name ob_m_2004
old name tec_m2004, new name tec_m_2004
old name adm_m2004, new name adm_m_2004
old name ob_m2005, new name ob_m_2005
old name tec_m2005, new name tec_m_2005
old name adm_m2005, new name adm_m_2005
old name ob_m2006, new name ob_m_2006
old name tec_m2006, new name tec_m_2006
old name adm_m2006, new name adm_m_2006
old name ob_m2007, new name ob_m_2007
old name tec_m2007, new name tec_m_2007
old name adm_m2007, new name adm_m_2007
old name ob_m2008, new name ob_m_2008
old name tec_m2008, new name tec_m_2008
old name adm_m2008, new name adm_m_2008
old name ob_m2009, new name ob_m_2009
old name tec_m2009, new name tec_m_2009
old name adm_m2009, new name adm_m_2009
old name ob_m2010, new name ob_m_2010
old name tec_m2010, new name tec_m_2010
old name adm_m2010, new name adm_m_2010
old name ob_m2011, new name ob_m_2011
old name tec_m2011, new name tec_m_2011
old name adm_m2011, new name adm_m_2011
old name ob_m2012, new name ob_m_2012
old name tec_m2012, new name tec_m_2012
old name adm_m2012, new name adm_m_2012
old name ob_m2014, new name ob_m_2014
old name tec_m2014, new name tec_m_2014
old name adm_m2014, new name adm_m_2014
old name ob_m2015, new name ob_m_2015
old name tec_m2015, new name tec_m_2015
old name adm_m2015, new name adm_m_2015
old name ob_m2016, new name ob_m_2016
old name tec_m2016, new name tec_m_2016
old name adm_m2016, new name adm_m_2016
old name ent2000, new name ent_2000
old name ent2001, new name ent_2001
old name ent2002, new name ent_2002
old name ent2003, new name ent_2003
old name ent2004, new name ent_2004
old name ent2005, new name ent_2005
old name ent2006, new name ent_2006
old name ent2007, new name ent_2007
old name ent2008, new name ent_2008
old name ent2009, new name ent_2009
old name ent2010, new name ent_2010
old name ent2011, new name ent_2011
old name ent2012, new name ent_2012
old name ent2013, new name ent_2013
old name ent2014, new name ent_2014
old name ent2015, new name ent_2015
old name ent2016, new name ent_2016
old name ele2000, new name ele_2000
old name ele2001, new name ele_2001
old name ele2002, new name ele_2002
old name ele2003, new name ele_2003
old name ele2004, new name ele_2004
old name ele2005, new name ele_2005
old name ele2006, new name ele_2006
old name ele2007, new name ele_2007
old name ele2008, new name ele_2008
old name ele2009, new name ele_2009
old name ele2010, new name ele_2010
old name ele2011, new name ele_2011
old name ele2012, new name ele_2012
old name ele2013, new name ele_2013
old name ele2014, new name ele_2014
old name ele2015, new name ele_2015
old name ele2016, new name ele_2016
old name com2000, new name com_2000
old name com2001, new name com_2001
old name com2002, new name com_2002
old name com2003, new name com_2003
old name com2004, new name com_2004
old name com2005, new name com_2005
old name com2006, new name com_2006
old name com2007, new name com_2007
old name com2008, new name com_2008
old name com2009, new name com_2009
old name com2010, new name com_2010
old name com2011, new name com_2011
old name com2012, new name com_2012
old name com2013, new name com_2013
old name com2014, new name com_2014
old name com2015, new name com_2015
old name com2016, new name com_2016
old name inf2000, new name inf_2000
old name inf2001, new name inf_2001
old name inf2002, new name inf_2002
old name inf2003, new name inf_2003
old name inf2004, new name inf_2004
old name inf2005, new name inf_2005
old name inf2006, new name inf_2006
old name inf2007, new name inf_2007
old name inf2008, new name inf_2008
old name inf2009, new name inf_2009
old name inf2010, new name inf_2010
old name inf2011, new name inf_2011
old name inf2012, new name inf_2012
old name inf2013, new name inf_2013
old name inf2014, new name inf_2014
old name inf2015, new name inf_2015
old name inf2016, new name inf_2016
old name wat2000, new name wat_2000
old name wat2001, new name wat_2001
old name wat2002, new name wat_2002
old name wat2003, new name wat_2003
old name wat2004, new name wat_2004
old name wat2005, new name wat_2005
old name wat2006, new name wat_2006
old name wat2007, new name wat_2007
old name wat2008, new name wat_2008
old name wat2009, new name wat_2009
old name wat2010, new name wat_2010
old name wat2011, new name wat_2011
old name wat2012, new name wat_2012
old name wat2013, new name wat_2013
old name wat2014, new name wat_2014
old name wat2015, new name wat_2015
old name wat2016, new name wat_2016
old name tss2000, new name tss_2000
old name tss2001, new name tss_2001
old name tss2002, new name tss_2002
old name tss2003, new name tss_2003
old name tss2004, new name tss_2004
old name tss2005, new name tss_2005
old name tss2006, new name tss_2006
old name tss2007, new name tss_2007
old name tss2008, new name tss_2008
old name tss2009, new name tss_2009
old name tss2010, new name tss_2010
old name tss2011, new name tss_2011
old name tss2012, new name tss_2012
old name tss2013, new name tss_2013
old name tss2014, new name tss_2014
old name tss2015, new name tss_2015
old name tss2016, new name tss_2016
old name buiilt2000, new name buiilt_2000
old name buiilt2001, new name buiilt_2001
old name buiilt2002, new name buiilt_2002
old name buiilt2003, new name buiilt_2003
old name buiilt2004, new name buiilt_2004
old name buiilt2005, new name buiilt_2005
old name buiilt2006, new name buiilt_2006
old name buiilt2007, new name buiilt_2007
old name buiilt2008, new name buiilt_2008
old name buiilt2009, new name buiilt_2009
old name buiilt2010, new name buiilt_2010
old name buiilt2011, new name buiilt_2011
old name buiilt2012, new name buiilt_2012
old name buiilt2013, new name buiilt_2013
old name buiilt2014, new name buiilt_2014
old name buiilt2015, new name buiilt_2015
old name buiilt2016, new name buiilt_2016
old name ocu2000, new name ocu_2000
old name ocu2001, new name ocu_2001
old name ocu2002, new name ocu_2002
old name ocu2003, new name ocu_2003
old name ocu2004, new name ocu_2004
old name ocu2005, new name ocu_2005
old name ocu2006, new name ocu_2006
old name ocu2007, new name ocu_2007
old name ocu2008, new name ocu_2008
old name ocu2009, new name ocu_2009
old name ocu2010, new name ocu_2010
old name ocu2011, new name ocu_2011
old name ocu2012, new name ocu_2012
old name ocu2013, new name ocu_2013
old name ocu2014, new name ocu_2014
old name ocu2015, new name ocu_2015
old name ocu2016, new name ocu_2016
old name sal_op2000, new name sal_op_2000
old name sal_op2001, new name sal_op_2001
old name sal_op2002, new name sal_op_2002
old name sal_op2003, new name sal_op_2003
old name sal_op2004, new name sal_op_2004
old name sal_op2005, new name sal_op_2005
old name sal_op2006, new name sal_op_2006
old name sal_op2007, new name sal_op_2007
old name sal_op2008, new name sal_op_2008
old name sal_op2009, new name sal_op_2009
old name sal_op2010, new name sal_op_2010
old name sal_op2011, new name sal_op_2011
old name sal_op2012, new name sal_op_2012
old name sal_op2013, new name sal_op_2013
old name sal_op2014, new name sal_op_2014
old name sal_op2015, new name sal_op_2015
old name sal_op2016, new name sal_op_2016
old name sal_tec2000, new name sal_tec_2000
old name sal_tec2001, new name sal_tec_2001
old name sal_tec2002, new name sal_tec_2002
old name sal_tec2003, new name sal_tec_2003
old name sal_tec2004, new name sal_tec_2004
old name sal_tec2005, new name sal_tec_2005
old name sal_tec2006, new name sal_tec_2006
old name sal_tec2007, new name sal_tec_2007
old name sal_tec2008, new name sal_tec_2008
old name sal_tec2009, new name sal_tec_2009
old name sal_tec2010, new name sal_tec_2010
old name sal_tec2011, new name sal_tec_2011
old name sal_tec2012, new name sal_tec_2012
old name sal_tec2013, new name sal_tec_2013
old name sal_tec2014, new name sal_tec_2014
old name sal_tec2015, new name sal_tec_2015
old name sal_tec2016, new name sal_tec_2016

In [34]:
sez_filtered

,code,name,latitude,longitude,start,close,type,sez_id,origin,inv_2000,...,sal_tec_2007,sal_tec_2008,sal_tec_2009,sal_tec_2010,sal_tec_2011,sal_tec_2012,sal_tec_2013,sal_tec_2014,sal_tec_2015,sal_tec_2016
0,DOM-6NO,Zona Franca 6 de Noviembre,18.434236,-70.077097,2016.0,0.0,private,1.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2500.00
1,DOM-ALC,Los Alcarrizos,18.521192,-70.050865,1990.0,0.0,public,2.0,1.0,19853638.95,...,3446.06,2969.16,4073.59,3389.04,3762.00,3197.77,3533.52,3852.34,4420.89,4293.00
2,DOM-ALT,Villa Altagracia,18.687048,-70.180632,1988.0,0.0,private,3.0,1.0,33900000.00,...,3489.29,3026.84,4079.53,2903.04,5212.50,4772.18,4996.25,5007.53,5640.68,5610.00
3,DOM-AND,Andres,18.442336,-69.649780,2009.0,0.0,private,4.0,1.0,0.00,...,0.00,0.00,3514.00,3675.25,3654.00,6025.00,5077.00,7045.37,6936.53,7100.00
4,DOM-ARM,La Armeria,18.421294,-70.117660,1990.0,0.0,public,5.0,1.0,8620740.19,...,1954.00,2551.00,3551.60,3893.25,3359.33,3131.93,4402.00,3956.30,4300.90,4187.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,DOM-VEG,La Vega,19.246732,-70.556490,1987.0,0.0,public,91.0,1.0,45018217.52,...,3836.31,2984.12,3021.27,3190.84,3356.29,3686.81,3737.21,4189.40,4754.71,4671.84
92,DOM-VER,Luperon Verde,19.793250,-70.680905,2019.0,0.0,private,92.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
93,DOM-VIS,Bella Vista,18.613215,-69.708447,2004.0,0.0,private,93.0,1.0,0.00,...,0.00,4569.00,4615.00,5375.00,4698.00,6863.00,6433.17,7015.64,4450.00,4500.00
94,DOM-YAQ,Parque Industrial y de Servicios Yaque,19.469724,-70.714373,2010.0,0.0,private,94.0,1.0,0.00,...,0.00,0.00,0.00,3439.60,4800.00,3417.45,3807.43,2897.10,3996.96,5841.01
96,DOM-ZOF,Zofinma (Mao),19.553957,-71.091628,1993.0,2006.0,private,95.0,1.0,413004.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [35]:
sez_filtered

,code,name,latitude,longitude,start,close,type,sez_id,origin,inv_2000,...,sal_tec_2007,sal_tec_2008,sal_tec_2009,sal_tec_2010,sal_tec_2011,sal_tec_2012,sal_tec_2013,sal_tec_2014,sal_tec_2015,sal_tec_2016
0,DOM-6NO,Zona Franca 6 de Noviembre,18.434236,-70.077097,2016.0,0.0,private,1.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2500.00
1,DOM-ALC,Los Alcarrizos,18.521192,-70.050865,1990.0,0.0,public,2.0,1.0,19853638.95,...,3446.06,2969.16,4073.59,3389.04,3762.00,3197.77,3533.52,3852.34,4420.89,4293.00
2,DOM-ALT,Villa Altagracia,18.687048,-70.180632,1988.0,0.0,private,3.0,1.0,33900000.00,...,3489.29,3026.84,4079.53,2903.04,5212.50,4772.18,4996.25,5007.53,5640.68,5610.00
3,DOM-AND,Andres,18.442336,-69.649780,2009.0,0.0,private,4.0,1.0,0.00,...,0.00,0.00,3514.00,3675.25,3654.00,6025.00,5077.00,7045.37,6936.53,7100.00
4,DOM-ARM,La Armeria,18.421294,-70.117660,1990.0,0.0,public,5.0,1.0,8620740.19,...,1954.00,2551.00,3551.60,3893.25,3359.33,3131.93,4402.00,3956.30,4300.90,4187.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,DOM-VEG,La Vega,19.246732,-70.556490,1987.0,0.0,public,91.0,1.0,45018217.52,...,3836.31,2984.12,3021.27,3190.84,3356.29,3686.81,3737.21,4189.40,4754.71,4671.84
92,DOM-VER,Luperon Verde,19.793250,-70.680905,2019.0,0.0,private,92.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
93,DOM-VIS,Bella Vista,18.613215,-69.708447,2004.0,0.0,private,93.0,1.0,0.00,...,0.00,4569.00,4615.00,5375.00,4698.00,6863.00,6433.17,7015.64,4450.00,4500.00
94,DOM-YAQ,Parque Industrial y de Servicios Yaque,19.469724,-70.714373,2010.0,0.0,private,94.0,1.0,0.00,...,0.00,0.00,0.00,3439.60,4800.00,3417.45,3807.43,2897.10,3996.96,5841.01
96,DOM-ZOF,Zofinma (Mao),19.553957,-71.091628,1993.0,2006.0,private,95.0,1.0,413004.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [36]:
col_mod

'sal_tec_2016'

In [37]:
long_sez_data = pd.melt(sez_filtered,
                id_vars=["code","name", "latitude", "longitude", "start", "close", "type"],
            value_vars=columns_mod)

In [38]:
long_sez_data

,code,name,latitude,longitude,start,close,type,variable,value
0,DOM-6NO,Zona Franca 6 de Noviembre,18.434236,-70.077097,2016.0,0.0,private,inv_2000,0.00
1,DOM-ALC,Los Alcarrizos,18.521192,-70.050865,1990.0,0.0,public,inv_2000,19853638.95
2,DOM-ALT,Villa Altagracia,18.687048,-70.180632,1988.0,0.0,private,inv_2000,33900000.00
3,DOM-AND,Andres,18.442336,-69.649780,2009.0,0.0,private,inv_2000,0.00
4,DOM-ARM,La Armeria,18.421294,-70.117660,1990.0,0.0,public,inv_2000,8620740.19
...,...,...,...,...,...,...,...,...,...
27163,DOM-VEG,La Vega,19.246732,-70.556490,1987.0,0.0,public,sal_tec_2016,4671.84
27164,DOM-VER,Luperon Verde,19.793250,-70.680905,2019.0,0.0,private,sal_tec_2016,0.00
27165,DOM-VIS,Bella Vista,18.613215,-69.708447,2004.0,0.0,private,sal_tec_2016,4500.00
27166,DOM-YAQ,Parque Industrial y de Servicios Yaque,19.469724,-70.714373,2010.0,0.0,private,sal_tec_2016,5841.01
27167,DOM-ZOF,Zofinma (Mao),19.553957,-71.091628,1993.0,2006.0,private,sal_tec_2016,0.00

In [39]:
long_sez_data[["category","year"]] = long_sez_data["variable"].str.extract(r"([A-Za-z_]+)_([0-9]{4})")

In [40]:
long_sez_data["category"].unique().tolist()

['inv',
 'ob_f',
 'tec_f',
 'adm_f',
 'ob_m',
 'tec_m',
 'adm_m',
 'ent',
 'ele',
 'com',
 'inf',
 'wat',
 'tss',
 'buiilt',
 'ocu',
 'sal_op',
 'sal_tec']

In [41]:
category_map = {
 'inv': "Inversion Acumulada",
 'ob_f': "Obreros (femeninos)",
 'tec_f': "Tecnicos (femeninos)",
 'adm_f': "Administrativos (femeninos)" ,
 'ob_m': "Obreros (masculinos)",
 'tec_m': "Tecnicos (masculinos)",
 'adm_m': "Administrativos (masculinos)",
 'ent': "Numero de Empresas",
 'ele': "Gastos: Electricidad",
 'com': "Gastos: Telecomunicaciones",
 'inf': "Gastos: Infotep",
 'wat': "Gastos: Agua",
 'tss': "Gastos: TSS",
 'buiilt': "Naves Construidas",
 'ocu': "Naves Ocupadas",
 'sal_op': "Salario Operarios",
 'sal_tec': "Salario Tecnicos"
 }

In [42]:
long_sez_data["category_full"] = long_sez_data["category"].map(category_map)

In [43]:
long_sez_data.to_csv("extracted_data/sez_data/sez_aggregated_long.csv")

In [44]:
long_sez_data.columns

Index(['code', 'name', 'latitude', 'longitude', 'start', 'close', 'type',
       'variable', 'value', 'category', 'year', 'category_full'],
      dtype='object')

In [45]:
long_pivot_sez_data = long_sez_data.pivot_table(index=["code","name", "latitude", "longitude", "start", "close", "type", "year"],
                                               columns='category_full',
                                               values="value").reset_index()

In [57]:
long_pivot_sez_data = long_pivot_sez_data[long_pivot_sez_data["latitude"]!=0]

In [58]:
long_pivot_sez_data.to_csv("extracted_data/sez_data/sez_pivot_aggregated_long.csv")